import { redirect } from "next/navigation";

// The full, watermarked PDF handbook is generated by the Lacspace PDF engine on
// the main site. Bridge to it so /docs/pdf works on the platform today; when the
// PDF engine is ported here this becomes a native generator.
export function GET() {
  redirect("https://lacspace.com/docs/pdf");
}
